config/routes.rb
Rails.application.routes.draw do
  root to: 'images#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:index, :show, :create]
  
  resources :images
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        end
end

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <img class="mr-2 rounded" src="<%= gravatar_url(user, { size: 50 }) %>" alt="">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

<div class="center jumbotron">
  <div class="text-center">
    <h1>Welcome to the Microposts</h1>
    <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
  </div>
</div>

app/views/users/new.html.erb
<h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">ユーザー登録</h2>
<div class="">
    <div class="p-8 lg:w-1/2 mx-auto">
        <div class="bg-white rounded py-12 px-4 lg:px-24">
            <%= form_with(model: @user, local: true) do |f| %>
                <div class="px-4 py-5 bg-white space-y-2 sm:p-2">
                    <label for="price" class="block text-gray-700 text-base font-bold mb-2">ユーザー名</label>
                    <%= f.text_field :name, class: ' appearance-none border pl-3 border-gray-300 shadow-sm focus:shadow-md focus:placeholder-gray-800  transition  rounded-md w-full py-3 text-gray-800 leading-tight focus:outline-none focus:ring-gray-800 focus:shadow-outline' %>
                </div>

                <div class="px-4 py-5 bg-white space-y-2 sm:p-2">
                    <label for="price" class="block text-gray-700 text-base font-bold mb-2">メールアドレス</label>
                    <%= f.email_field :email, class: ' appearance-none border pl-3 border-gray-300 shadow-sm focus:shadow-md focus:placeholder-gray-800  transition  rounded-md w-full py-3 text-gray-800 leading-tight focus:outline-none focus:ring-gray-800 focus:shadow-outline' %>
                </div>

                <div class="px-4 py-5 bg-white space-y-2 sm:p-2">
                    <label for="price" class="block text-gray-700 text-base font-bold mb-2">パスワード</label>
                    <%= f.password_field :password, class: 'appearance-none border pl-3 border-gray-300 shadow-sm focus:shadow-md focus:placeholder-gray-800  transition  rounded-md w-full py-3 text-gray-800 leading-tight focus:outline-none focus:ring-gray-800 focus:shadow-outline' %>
                </div>

                <div class="px-4 py-5 bg-white space-y-2 sm:p-2">
                    <label for="price" class="block text-gray-700 text-base font-bold mb-2">パスワード確認</label>
                    <%= f.password_field :password_confirmation, class: ' appearance-none border pl-3 border-gray-300 shadow-sm focus:shadow-md focus:placeholder-gray-800  transition  rounded-md w-full py-3 text-gray-800 leading-tight focus:outline-none focus:ring-gray-800 focus:shadow-outline' %>
                </div>

                <div class="flex items-center justify-center mt-8">
                    <%= button_tag :type => "submit", :class =>"text-white py-2 px-4 uppercase rounded bg-indigo-500 hover:bg-indigo-600 shadow hover:shadow-lg font-medium transition transform hover:-translate-y-0.5" do %>
                        <i class="fas fa-user-edit"></i>  登録する
                    <% end %>
                </div>
            <% end %>
        </div>
    </div>
</div>